spring:
  # DataSource properties
  datasource:
    url: jdbc:mariadb://localhost:3307/product-manager
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  # Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
springdoc:
  default-produces-media-type: application/json

  flyway:
    url: jdbc:mariadb://localhost:3307/product-manager
    user: root
    password:
    springdoc:
      default-produces-media-type: application/json